name: Deploy Backend to Production

on:
  workflow_dispatch:  # Запуск процесса вручную с кнопки "Run workflow"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Setup
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "Setting up SSH environment..."

          # Проверка и установка SSH клиента
          command -v ssh-agent >/dev/null || (apt-get update -y && apt-get install openssh-client -y)

          # Запуск ssh-agent и добавление ключа
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -

          # Настройка SSH файлов
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod -R 400 ~/.ssh
          
          echo "SSH setup completed."

      - name: Deploy to Timeweb
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Starting deployment process..."

          # Проверяем SSH-подключение
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH connection successful!'"

          # Подключаемся к серверу и выполняем команды
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            echo "Connected to server. Starting deployment commands..."
            cd /path/to/itdudes-backend

            echo "Pulling latest changes from develop branch..."
            git fetch origin
            git rebase origin/develop

            echo "Installing dependencies and building project..."
            npm install
            npm run build

            echo "Restarting backend with pm2..."
            pm2 delete backend || true
            pm2 start dist/index.js --name backend

            echo "Deployment commands completed."
          EOF

          echo "Deployment process completed."
